. .\.venv\Scripts\Activate.ps1

$env:PYTHONPATH = "src"

python -c "import onnxruntime as ort; print('ONNX Runtime:', ort.__version__); print('Providers:', ort.get_available_providers())"
python -c "from pathlib import Path; paths = ['models/mediapipe/face_landmarker_v2.task', 'models/mediapipe/pose_landmarker.task', 'models/onnx/yolox_tiny.onnx', 'models/onnx/yolox_s.onnx', 'models/onnx/facial_expression_recognition_mobilefacenet_2022july.onnx', 'models/onnx/face_detection_yunet_2023mar.onnx']; [print(path, Path(path).exists()) for path in paths]"
python -c "import numpy as np; from classroom_engagement.pipeline.components import build_detector; det = build_detector('yolox_onnx', {'weights': 'models/onnx/yolox_tiny.onnx', 'input_width': 416, 'input_height': 416, 'providers': ['DmlExecutionProvider', 'CPUExecutionProvider']}); result = det.detect(np.zeros((480, 640, 3), dtype=np.uint8)); print('YOLOX tiny smoke test detections:', len(result))"
python -c "import cv2, numpy as np; from classroom_engagement.pipeline.signals import OnnxExpressionAnalyzer; img = np.full((220, 180, 3), 210, dtype=np.uint8); cv2.circle(img, (90, 92), 54, (170, 170, 170), -1); cv2.circle(img, (72, 82), 7, (40, 40, 40), -1); cv2.circle(img, (108, 82), 7, (40, 40, 40), -1); cv2.ellipse(img, (90, 110), (20, 12), 0, 0, 180, (50, 50, 50), 3); analyzer = OnnxExpressionAnalyzer({'weights': 'models/onnx/facial_expression_recognition_mobilefacenet_2022july.onnx', 'providers': ['DmlExecutionProvider', 'CPUExecutionProvider'], 'face_detector': {'enabled': True, 'model_path': 'models/onnx/face_detection_yunet_2023mar.onnx'}}); feature = analyzer.analyze(img, track_id=1); print('Expression analyzer smoke test:', feature is not None)"
python -c "import numpy as np; from classroom_engagement.pipeline.engine import PipelineEngine; engine = PipelineEngine(detector_name='yolox_onnx', tracker_name='bytetrack'); result = engine.process_frame(np.zeros((480, 640, 3), dtype=np.uint8), timestamp=0.0, source_name='validation'); print('Pipeline smoke test state:', result.class_snapshot.state, 'count=', result.class_snapshot.student_count)"
python -c "from classroom_engagement.settings import get_settings; cfg = get_settings().load_models_config().get('models', {}); print('Configured detector:', cfg.get('detector', {}).get('name')); print('Configured detector providers:', cfg.get('detector', {}).get('providers')); print('Expression analyzer enabled:', cfg.get('expression', {}).get('enabled')); print('YuNet enabled:', cfg.get('expression', {}).get('face_detector', {}).get('enabled')); print('Pose analyzer enabled:', cfg.get('pose', {}).get('enabled'))"
